-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME,RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT P.ITEM_ID
    FROM ITEM_TREE P
    LEFT JOIN ITEM_TREE C ON C.PARENT_ITEM_ID = P.ITEM_ID
    WHERE C.ITEM_ID IS NULL
)
ORDER BY 1 DESC;