-- 코드를 작성해주세요

SELECT 
    P.ID, 
    CASE WHEN COUNT(C.ID) IS NULL THEN 0 ELSE COUNT(C.ID) END AS CHILD_COUNT
FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA C ON P.ID = C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID