-- 코드를 입력하세요
SELECT
    DATE_FORMAT(N.SALES_DATE,"%Y-%m-%d") AS SALES_DATE,
    N.PRODUCT_ID,
    USER_ID,
    SUM(N.SALES_AMOUNT) AS SALES_AMOUNT
FROM ONLINE_SALE N
LEFT JOIN OFFLINE_SALE F ON N.PRODUCT_ID = F.PRODUCT_ID
WHERE DATE_FORMAT(N.SALES_DATE,"%Y-%m") = '2022-03' 
GROUP BY N.PRODUCT_ID
ORDER BY N.SALES_DATE, N.PRODUCT_ID, USER_ID;