-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID 
AND I.SEX_UPON_INTAKE LIKE 'Intact%' 
AND O.SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
ORDER BY O.ANIMAL_ID;
    