-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(CAR_ID) CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%'
    OR OPTIONS LIKE '%열선시트%' 
    OR OPTIONS LIKE '%가죽시트%'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE


--정규표현식을 이용한 다른 풀이
SELECT CAR_TYPE, COUNT(CAR_ID) CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS REGEXP '통풍시트|열선시트|가죽시트'
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE

💡`REGEXP 'A|B|C|'`는 A,B,C중 하나라도 포함하면 TRUE를 반환
💡`FIND_IN_SET('값', 컬럼명)`은 쉼표로 구분된 값 중 특정 값이 포함된 경우 TRUE를 반환

--FIND_IN_SET을 이용한 다른 풀이
SELECT CAR_TYPE, COUNT(CAR_ID) CARS
FROM CAR_RENTAL_COMPNAY_CAR
WHERE FIND_IN_SET('통풍시트', OPTIONS) 
    OR FIND_IN_SET('열선시트', OPTIONS)
    OR FIND_IN_SET('가죽시트', OPTIONS)
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE
