-- 코드를 입력하세요

SELECT
    HISTORY_ID,
    TRUNCATE(
        DAILY_FEE 
        * (DATEDIFF(END_DATE,START_DATE) + 1)
        * (1 - IFNULL(DISCOUNT_RATE,0) / 100) 
        , 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C 
    ON H.CAR_ID = C.CAR_ID 
    AND CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE 
    AND (
        (DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 AND DURATION_TYPE = '7일 이상')
        OR (DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 AND DURATION_TYPE = '30일 이상')
        OR (DATEDIFF(END_DATE, START_DATE) + 1 >= 90 AND DURATION_TYPE = '90일 이상')
    )
ORDER BY 2 DESC, 1 DESC;

