-- 코드를 입력하세요
SELECT J.FLAVOR
FROM (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ) J
JOIN FIRST_HALF F ON J.FLAVOR = F.FLAVOR
GROUP BY FLAVOR
ORDER BY (J.TOTAL_ORDER + F.TOTAL_ORDER) DESC
LIMIT 3