-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P ON A.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID and A.MCDP_CD = 'CS'
WHERE DATE_FORMAT(APNT_YMD, "%Y-%m-%d") = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;
