-- 코드를 입력하세요
WITH RECURSIVE TIME_COUNT AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_COUNT WHERE HOUR < 23
    )
SELECT 
    TC.HOUR AS HOUR,
    COALESCE(COUNT(A.ANIMAL_ID),0) AS COUNT
FROM TIME_COUNT AS TC
LEFT JOIN
    ANIMAL_OUTS A
    ON HOUR(A.DATETIME) = TC.HOUR
GROUP BY TC.HOUR
ORDER BY TC.HOUR;