WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS F_HOUR
    UNION ALL
    SELECT F_HOUR + 1
    FROM HOUR_TABLE
    WHERE F_HOUR < 23
) 

SELECT
    F_HOUR AS HOUR,
    COUNT(ANIMAL_ID) AS COUNT
FROM HOUR_TABLE H
LEFT JOIN ANIMAL_OUTS A ON HOUR(A.DATETIME) = H.F_HOUR
GROUP BY F_HOUR
ORDER BY 1;