-- 코드를 입력하세요
-- 완료된 중고거래 > status = DONE, 총금액 70만원 이상

SELECT 
    WRITER_ID,
    NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID AND STATUS = 'DONE'
GROUP BY WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY 3;

    