-- 코드를 입력하세요
WITH MAX AS (
    SELECT P.MEMBER_ID, MEMBER_NAME, COUNT(REVIEW_TEXT) AS REVIEW_CNT
    FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
    GROUP BY P.MEMBER_ID
    ORDER BY COUNT(REVIEW_TEXT) DESC
    LIMIT 1
    ) 

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MAX M
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY 3,2 