SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE (I.FISH_TYPE, LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I 
    GROUP BY FISH_TYPE
)
ORDER BY 1;