WITH BIGGEST_FISH AS(
SELECT 
    FISH_TYPE,
    MAX(LENGTH) AS LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE
)

# SELECT *
# FROM BIGGEST_FISH
SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I 
JOIN BIGGEST_FISH B ON I.FISH_TYPE = B.FISH_TYPE AND I.LENGTH = B.LENGTH
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE

ORDER BY 1;