# WITH MAX_PRICE_PRODUCT AS (
#         SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#         FROM FOOD_PRODUCT 
#         WHERE CATEGORY IN ('과자','국','김치','식용유')
#         GROUP BY CATEGORY
# )

# SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
# FROM FOOD_PRODUCT FP
# JOIN MAX_PRICE_PRODUCT MPR
# ON FP.CATEGORY = MPR.CATEGORY AND FP.PRICE = MPR.MAX_PRICE
# ORDER BY FP.PRICE DESC;










SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE)
                           FROM FOOD_PRODUCT
                           WHERE CATEGORY IN ('과자','국','김치','식용유')
                           GROUP BY CATEGORY)
ORDER BY PRICE DESC